version: '3.8'

services:
  dashboard:
    build: .
    container_name: brukd-customer-engagement
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./visualizations:/app/visualizations
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    networks:
      - brukd-network

networks:
  brukd-network:
    driver: bridge

